package io.intino.goros.modernizing.monet.renderers.templates.konos;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class ArtifactTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
			rule().condition((type("artifact"))).output(literal("dsl Legio\n\nArtifact(groupId = \"")).output(mark("package")).output(literal("\", version = \"1.0.0\") model as Product\n    Model(language = \"Unit\", version = \"1.2.2\", sdkVersion = \"4.1.2\")\n    Box(language = \"Konos\", version = \"9.4.5\")\n\n    Imports\n        Compile(\"io.intino.alexandria\", \"ui-framework\", \"4.19.13\")\n        Compile(\"io.intino.alexandria\", \"core-framework\", \"2.1.0\")\n\n        Web(\"")).output(mark("package")).output(literal("\", \"model-elements\", \"1.0.0\")\n\n        Test(groupId = \"junit\", artifactId = \"junit\", version = \"LATEST\")\n\n    Package(mode = ModulesAndLibrariesLinkedByManifest) as Runnable(mainClass=\" ")).output(mark("package")).output(literal(".")).output(mark("module", "lowerCase")).output(literal(".box.Main\")\n\n    Parameter(\"home\")\n    Parameter(\"port\")\n\nRepository(identifier = \"intino-maven\")\n    Release(url = \"https://artifactory.intino.io/artifactory/releases\")\n    Snapshot(url = \"https://artifactory.intino.io/artifactory/snapshots\")\n\nRunConfiguration local\n    Argument(\"workspace\", \"./temp\")\n    Argument(\"port\", \"9000\")\n    Argument(\"certificate-filename\", \"businessunit-monet.p12\")\n    Argument(\"certificate-password\", \"1234\")\n    Argument(\"jdbc-datasource\", \"jdbc/MonetDatabaseSource\")\n    Argument(\"jdbc-type\", \"mysql\")\n    Argument(\"jdbc-url\", \"jdbc:mysql://localhost:3306/monet?autoReconnect=true&amp;useSSL=false\")\n    Argument(\"jdbc-user\", \"root\")\n    Argument(\"jdbc-password\", \"\")\n    Argument(\"user-data-dir\", \"./temp/monet\")\n    Argument(\"component-documents-monet-url\", \"http://localhost:8080/docservice\")\n    Argument(\"component-documents-monet-is-shared\", \"true\")\n    Argument(\"component-datawarehouse-monet-url\", \"http://localhost:8081/sumus\")\n    Argument(\"services-base-url\", \"http://127.0.0.1:9000\")\n    Argument(\"mobile-fcm-settings-filename\", \"./temp/monet/settings-fcm.json\")\n    Argument(\"mobile-fcm-project-id\", \"\")\n    Argument(\"mobile-google-api-key\", \"\")\n    Argument(\"mail-admin-host\", \"smtp.gmail.com\")\n    Argument(\"mail-admin-host\", \"monet.org\")\n    Argument(\"mail-admin-from\", \"noreply@monet.org\")\n    Argument(\"mail-admin-to\", \"admin@monet.org\")\n    Argument(\"mail-admin-username\", \"admin\")\n    Argument(\"mail-admin-password\", \"\")\n    Argument(\"is-debug-mode\", \"false\")\n    Argument(\"store-directory\", \"./temp/monetfederation/store\")"))
		);
	}
}