package io.intino.goros.modernizing.monet.renderers.templates.konos;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class FormDefinitionTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
			rule().condition((allTypes("show","fields")), (trigger("use"))).output(expression().output(mark("field", "use").multiple("\n"))),
			rule().condition((allTypes("show","fields"))).output(literal("Block content as Relative(width=90%)\n    ")).output(expression().output(mark("field").multiple("\n"))),
			rule().condition((allTypes("show","location"))).output(literal("Text(value=\"TODO\")")),
			rule().condition((allTypes("show","layout")), (trigger("use"))).output(expression().output(mark("row", "use").multiple("\n"))),
			rule().condition((allTypes("show","layout"))).output(literal("Block")).output(expression().output(literal(" ")).output(mark("absoluteFacet"))).output(expression().output(literal(" ")).output(mark("relativeFacet"))).output(literal("\n    ")).output(expression().output(mark("row").multiple("\n"))),
			rule().condition((type("layoutRow")), (trigger("use"))).output(expression().output(mark("element", "use").multiple("\n"))),
			rule().condition((type("layoutRow"))).output(literal("Block(layout=Horizontal Flexible)\n    ")).output(expression().output(mark("element").multiple("\n"))),
			rule().condition((allTypes("layoutElement","section")), (trigger("use"))).output(expression().output(mark("row", "use").multiple("\n"))),
			rule().condition((type("layoutElement")), (trigger("use"))).output(expression().output(mark("field", "use"))),
			rule().condition((allTypes("layoutElement","section"))).output(literal("Block(layout=Vertical Flexible)\n    ")).output(expression().output(literal("Text(value=\"")).output(mark("label")).output(literal("\")"))).output(literal("\n    ")).output(expression().output(mark("row").multiple("\n"))),
			rule().condition((allTypes("layoutElement","space"))).output(literal("Text(value=\" \")")),
			rule().condition((type("layoutElement"))).output(literal("Block(format=airRight)")).output(expression().output(literal(" ")).output(mark("absoluteFacet"))).output(expression().output(literal(" ")).output(mark("relativeFacet"))).output(literal("\n    ")).output(mark("field")),
			rule().condition((type("absoluteFacet"))).output(literal("as Absolute(")).output(expression().output(literal("width=")).output(mark("width")).output(literal("px"))).output(expression().output(mark("width", "empty")).output(literal(","))).output(expression().output(literal("height=")).output(mark("height")).output(literal("px"))).output(literal(")")),
			rule().condition((type("relativeFacet"))).output(literal("as Relative(")).output(expression().output(literal("width=")).output(mark("width")).output(literal("%"))).output(expression().output(mark("width", "empty")).output(literal(","))).output(expression().output(literal("height=")).output(mark("height")).output(literal("%"))).output(literal(")")),
			rule().condition((trigger("empty"))),
			rule().condition((allTypes("field","link")), (trigger("use"))).output(literal("use ")).output(mark("index", "firstUpperCase")),
			rule().condition((allTypes("field","composite")), (trigger("use"))).output(expression().output(mark("field", "use").multiple("\n"))),
			rule().condition((type("field")), (trigger("use"))),
			rule().condition((allTypes("field","text","multiple"))).output(literal("Text(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Multiple(noItemsMessage=\"No hay elementos\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly > Count(min=")).output(mark("min")).output(literal(", max=")).output(mark("max")).output(literal(")")),
			rule().condition((allTypes("field","text"))).output(literal("Text(format=airBottom")).output(expression().output(literal(", mode=")).output(mark("textMode"))).output(literal(") ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable(helperText=\"Rellene aquí el valor del campo\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","number","multiple"))).output(literal("Number(format=airBottom, min=")).output(mark("min")).output(literal(", max=")).output(mark("max")).output(literal(") ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Multiple(noItemsMessage=\"No hay medidas\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","number"))).output(literal("Number(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","boolean"))).output(literal("Switch(format=airBottom, title=\"")).output(mark("label")).output(literal("\") ")).output(mark("name", "firstLowerCase")).output(literal(" as Action Readonly")),
			rule().condition((allTypes("field","date","multiple"))).output(literal("Date(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Multiple(\"No ha indicado fechas\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","date"))).output(literal("Date(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","memo","multiple"))).output(literal("Text(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Multiple(noItemsMessage=\"No hay elementos\") Labeled(\"")).output(mark("label")).output(literal("\") Memo Readonly > Count(min=")).output(mark("min")).output(literal(", max=")).output(mark("max")).output(literal(")")),
			rule().condition((allTypes("field","memo"))).output(literal("Text(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Labeled(\"")).output(mark("label")).output(literal("\") Memo Readonly")),
			rule().condition((allTypes("field","serial"))).output(literal("Text(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","file","multiple"))).output(literal("File(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable(showPreview=true) Multiple(noItemsMessage=\"No hay documentos\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","file"))).output(literal("File(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable(showDropZone=true) Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","picture","multiple"))).output(literal("Image(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable(showPreview=true) Multiple(noItemsMessage=\"No hay imágenes\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly Absolute(width=150px,height=150px)")),
			rule().condition((allTypes("field","picture"))).output(literal("Image(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as Editable(showPreview=true) Labeled(\"")).output(mark("label")).output(literal("\") Readonly Absolute(width=150px,height=150px)")),
			rule().condition((allTypes("field","check"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as CheckBox(layout=Vertical) Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","link","multiple"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as CollectionBox(source=")).output(mark("index", "firstUpperCase")).output(mark("indexView", "firstUpperCase")).output(literal("Table, multipleSelection=true, placeholder=\"Seleccione un valor\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","link"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as CollectionBox(source=")).output(mark("index", "firstUpperCase")).output(mark("indexView", "firstUpperCase")).output(literal("Table, placeholder=\"Seleccione un valor\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","select","multiple"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as ComboBox(placeholder=\"Seleccione un valor\", multipleSelection=true) Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","select","inline"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as ListBox Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","select"))).output(literal("Selector(format=airBottom) ")).output(mark("name", "firstLowerCase")).output(literal(" as ComboBox(placeholder=\"Seleccione un valor\") Labeled(\"")).output(mark("label")).output(literal("\") Readonly")),
			rule().condition((allTypes("field","composite","multiple"))).output(literal("TemplateStamp(format=airBottom, template=")).output(mark("definition", "firstUpperCase")).output(mark("name", "firstUpperCase")).output(literal("Template) ")).output(mark("name", "firstLowerCase")).output(literal(" as Multiple(noItemsMessage=\"No hay elementos\", collapsed=true) Editable Labeled(\"")).output(mark("label")).output(literal("\")")),
			rule().condition((allTypes("field","composite"))).output(literal("TemplateStamp(format=airBottom, template=")).output(mark("definition", "firstUpperCase")).output(mark("name", "firstUpperCase")).output(literal("Template) ")).output(mark("name", "firstLowerCase")),
			rule().condition((allTypes("field","node","multiple"))).output(literal("OwnerTemplateStamp(format=airBottom, template=\"FieldNodeTemplate\", owner=")).output(mark("module", "firstUpperCase")).output(literal("Elements.goros) ")).output(mark("name", "firstLowerCase")).output(literal(" as Multiple(noItemsMessage=\"No hay elementos\") Editable Labeled(\"")).output(mark("label")).output(literal("\")")),
			rule().condition((allTypes("field","node"))).output(literal("OwnerTemplateStamp(format=airBottom, template=\"FieldNodeTemplate\", owner=")).output(mark("module", "firstUpperCase")).output(literal("Elements.goros) ")).output(mark("name", "firstLowerCase")),
			rule().condition((type("compositeView"))).output(literal("Template(format=compositeFieldStyle) ")).output(mark("definition", "firstUpperCase")).output(mark("name", "firstUpperCase")).output(literal("Template\n    Text(format=h5 airBottom, value=\"")).output(mark("label")).output(literal("\")\n    ")).output(mark("show"))
		);
	}
}